services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: shortorg
      POSTGRES_PASSWORD: shortorg
      POSTGRES_DB: shortorg
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  db_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: shortorg
      POSTGRES_PASSWORD: shortorg
      POSTGRES_DB: shortorg
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data
  identity_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: identity
      POSTGRES_DB: identity
    ports:
      - "5434:5432"
    volumes:
      - identity_db:/var/lib/postgresql/data
  identity_db_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: identity
      POSTGRES_DB: identity
    ports:
      - "5435:5432"
    volumes:
      - identity_db_test:/var/lib/postgresql/data
volumes:
  db_data:
  db_test_data:
  identity_db:
  identity_db_test:
