services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: shortorg
      POSTGRES_PASSWORD: shortorg
      POSTGRES_DB: shortorg
      TZ: America/New_York
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  db_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: shortorg
      POSTGRES_PASSWORD: shortorg
      POSTGRES_DB: shortorg
      TZ: America/New_York
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  identity_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: identity
      POSTGRES_DB: identity
      TZ: America/New_York
    ports:
      - "5434:5432"
    volumes:
      - identity_db:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  identity_db_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: identity
      POSTGRES_DB: identity
      TZ: America/New_York
    ports:
      - "5435:5432"
    volumes:
      - identity_db_test:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf  # Mount redis.conf from config
      - redis_data:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]  # Use custom redis.conf
    restart: always
volumes:
  db_data:
  db_test_data:
  identity_db:
  identity_db_test:
  redis_data:
    driver: local
