Env = "dev"
EncodedUrlsQueSize = 10000
Concurrency = 2
IsDebug = false

[APIServer]
Host = "localhost"

[APIServer.HTTP]
InternalPort = 8080

[Infrastructure.TokenStore]
BufferSize = 1000

[Infrastructure.Cache]
UseCache = false
MaxNumberOfElements = 1000
MaxMbSize = 512

[Infrastructure.PostgresClients.TokenIdentifier]
User = "identity"
Password = "identity"
Host = "localhost"
DBName = "identity"
Port = 5434
MaxConnections = 4
MaxIdleConnections = 4

[Infrastructure.PostgresClients.ShortOrg]
User = "shortorg"
Password = "shortorg"
Host = "localhost"
DBName = "shortorg"
Port = 5432
MaxConnections = 40
MaxIdleConnections = 40
