concurrency = 2
encoded_urls_queue_size = 10000
use_cache = false
debug = true
env = "development"

[api_server]
host = "localhost"

[api_server.http]
internal_port = 8080

[postgres_clients.token_identifier]
user = "identity"
password = "identity"
host = "localhost"
dbname = "identity"
port = 5434
max_connections = 4
max_idle_connections = 4

[postgres_clients.short_org]
user = "shortorg"
password = "shortorg"
host = "localhost"
dbname = "shortorg"
port = 5432
max_connections = 40
max_idle_connections = 40

[cache]
max_number_of_elements = 100000
max_mb_size = 512
